// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectory():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
